version: '3.8'
services:
  rl_mldl:
    build: 
      context: .
      platforms:
        - "linux/amd64"
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - MUJOCO_PY_MUJOCO_PATH=/opt/mujoco210
      - LD_LIBRARY_PATH=/opt/mujoco210/bin
    command: bash

